#!/bin/sh
DMENULINES=15

help () {
    echo "Call without an argument to be prompted with dmenu."
    echo "Flags:"
    printf "-h, --help\n-c, --copy\n-a, --add\n-e, --edit\n"
}
copy () {
    sort -t2 "$BOOKMARKS" | dmenu -l $DMENULINES -p "bookmark:" | cut -f 1 | xclip -i -selection clipboard
}
add () {

}
edit () {

}

promptflag () {
    prompt="$(printf 'copy\nadd\nedit')"
    action="$(dmenu -l 3 -p '$prompt')"
    [ "$action" = "copy" ] && copy
    [ "$action" = "edit" ] && edit
    [ "$action" = "add" ] && add
}
argparse () {
    arg="$1"
    [ "$1" = '-h' ] || [ "$1" = '--help' ] && help && exit 0
    [ "$1" = '-c' ] || [ "$1" = '--copy' ] && copy && exit 0
    [ "$1" = '-a' ] || [ "$1" = '--add' ]  && add && exit 0
    [ "$1" = '-e' ] || [ "$1" = '--edit' ] && edit && exit 0
    [ -z "$1" ] && promptflag
}

[ -z "$2" ] && argparse "$1" || echo "Too many arguments: use one or none." && exit 1
