#!/bin/sh

# sbm-setup: tasks of the Windows installer.
#
#     sbm-setup data    give the user the example tags and search keywords,
#                       and keep the files that the user has
#     sbm-setup stop    stop the bm-watch that the installer started

case ${1-} in
    data)
        d=${XDG_DATA_HOME:-$HOME/.local/share}/sbm
        mkdir -p "$d"
        for f in engines usertags; do
            [ -e "$d/$f" ] || cp "/usr/local/share/sbm/$f" "$d/"
        done
        ;;
    stop)
        # The hidden mintty of bm-watch has the class sbm-watch. When it
        # stops, bm-watch gets SIGHUP and stops too. Cygwin shows the
        # arguments of a process in /proc/PID/cmdline.
        for f in /proc/[0-9]*/cmdline; do
            case $(tr '\0' ' ' < "$f" 2>/dev/null) in
                *'--class sbm-watch '*)
                    pid=${f#/proc/}
                    kill "${pid%/cmdline}" 2>/dev/null
                    ;;
            esac
        done
        ;;
    *)
        printf 'usage: sbm-setup data | stop\n' >&2
        exit 2
        ;;
esac
